background #101714
foreground #dce8df
selection_background #35483d
selection_foreground #dce8df
cursor #dce8df
color0  #1d2a23
color8  #607568
color1  #d87878
color9  #d87878
color2  #8fbc9f
color10 #8fbc9f
color3  #d6b86a
color11 #d6b86a
color4  #6fae8f
color12 #6fae8f
color5  #8fbc9f
color13 #8fbc9f
color6  #6fbf8f
color14 #6fbf8f
color7  #dce8df
color15 #ffffff

background_opacity 0.85
