require("modules.env")
require("modules.rules")
require("modules.monitors")
require("modules.apps")
require("modules.autostart")
require("modules.apperance")
require("modules.input")
require("modules.binds")
